### ISSUE TITLE
[GUIDANCE] Selecting Tenant via OpenSearch Dashboards API

### ISSUE THREAD

**Issue by jkdll** [opensearch-project/security-dashboards-plugin#1002]
Hi,
I am currently using python to programmatically request a list of dashboards and perform imports of OpenSearch Dashboard Objects and exports OpenSearch dashboards. 

I authenticate using aws4auth:
```
awsauth = AWS4Auth(CREDENTIALS.access_key, CREDENTIALS.secret_key, REGION, SERVICE, session_token=CREDENTIALS.token)
```
And then perform some API calls against the Opensearch API Endpoint (Sample Code Below - currently untested). However, when I authenticate it seems like the private tenant is selected as the default, and any API calls hit the private tenant by default. 

I was wondering if there is a way to specify the tenant, either via a header or a parameter. Or perhaps, request a session token for a particular tenant prior to making these API calls. **Could you kindly offer advice as to how to do this?**

I believe a tool for moving around OpenSearch dashboard objects would be very useful and would be happy to share it if I manage to get it working.

````
def get_saved_objects(page_size = 200, page_no = 1, object_type = 'dashboard'):
    url_params = f"perPage={page_size}&page={page_no}&fields=name&type={object_type}"
    endpoint = f'https://{ConfigParams.HOST}/_dashboards/api/opensearch-dashboards/management/saved_objects/_find?{url_params}'
    response = requests.request(url=endpoint, method='GET', auth = ConfigParams.awsauth)
    return response

def export_object(object_id, object_type, include_references = True):
    # Body Parameter to export dependencies
    dependency_param = 'true' if include_references is True else 'false'

    # Set Endpoint and build body
    endpoint = f'https://{ConfigParams.HOST}/_dashboards/api/saved_objects/_export'
    body = '{"objects": [{"id": "{}","type": "{}"}],"includeReferencesDeep": {}}'.format(object_id,object_type,dependency_param)

    # Perform Request and Return
    response = requests.request(url=endpoint, method='POST', auth = ConfigParams.awsauth, data = body)
    return response

def import_object(file_location, file_name, overwrite = True):
    # URL Parameter to Overwrite
    overwite_param = 'true' if overwrite is True else 'false'
    # https://stackoverflow.com/questions/12385179/how-to-send-a-multipart-form-data-with-requests-in-python
    fileobj = {'file': (file_name, open(file_location, 'rb'), 'application/ndjson', {'Expires': '0'})}
    # Set Endpoint and Build Body
    endpoint = f'https://{ConfigParams.HOST}/_dashboards/api/saved_objects/_import?overwrite={overwite_param}'
    response = requests.request(url=endpoint, method='POST', auth = ConfigParams.awsauth, files=fileobj )
    return response
```

**Comment by jkdll** [comment]
Thank you @kavilla - I would be happy to share, if we get this working.

**Comment by peternied** [comment]
@jkdll I would recommend you open a feature request in OpenSearch/Dashboards for exactly what you are attempting to build, it might be much easier to have it added to dashboards directly rather than as an utility working paired with a running instance.

The mechanisms that are used to determine the tenant in dashboards requests are in this code base and they are **not** considered part of the public API, so as a word of warning they could break malfunction on a minor version bump.

That said by using `securitytenant` in the query parameters/headers of the request to tell the security plugin how the request should be routed.  

https://github.com/opensearch-project/security-dashboards-plugin/blob/611ef5dc2ef2215fb7e826bd4ef608c78d0bfbc0/server/multitenancy/tenant_resolver.ts#L44-L59

I am closing out this issue, as I believe your core question has been answered.  But please comment if there is anything else outstanding.

**Comment by jkdll** [comment]
@peternied 
I've attempted to use the security_tenant header, as shown below:

```
def get_saved_objects(page_size = 200, page_no = 1, object_type = 'dashboard', tenant='TestTenant'):
    url_params = f"perPage={page_size}&page={page_no}&fields=name&type={object_type}"
    endpoint = f'https://{ConfigParams.HOST}/_dashboards/api/opensearch-dashboards/management/saved_objects/_find?{url_params}'
    response = requests.request(url=endpoint, method='GET', auth = ConfigParams.awsauth, headers = "{'security_tenant': '{}'}".format(tenant))
    return response
```

However I get the following error:
`KeyError: "'security_tenant'"`

This is the same for both securitytenant and security_tenant. It also does not work as a URL parameter.

Could you please guide me?
