### ISSUE TITLE
Easy Tenant Switcher

### ISSUE THREAD

**Issue by robputt** [opensearch-project/security-dashboards-plugin#103]
Hello,

We are deploying OpenDistro using LDAP and tenants, various LDAP users are able to use various tenants however switching between tenants on the fly isn't very pleasing today. Can we add a drop down tenant switcher next to the user's logout button in the top right of the Kibana window to easily allow users to switch tenants?

I think this would be a welcomed feature for many deployments along with the ability for user's to select a default tenant.

Best Regards,

Rob

**Comment by bgagnon** [comment]
The [Kibana Spaces](https://www.elastic.co/guide/en/kibana/master/xpack-spaces.html) placement and presentation seems ideal. Could this plugin use a similar look and feel?

**Comment by drock** [comment]
In addition to allowing for the easy switching of tenants, this would have an added benefit of allowing you to easily see which tenant you are currently working within.  Currently, its very frustrating because the only way to see which tenant you are in is to navigate away from what you are doing to the tenants menu and view what is selected.

This bit us as we were first learning how to use Open Distro Security as by default we were placed in our private tenant, but had no idea.

**Comment by cliu123** [comment]
The functionality has been added. Now user can switch tenants in the user name icon dropdown list easily.
![Screen Shot 2022-04-12 at 10.25.27 AM.png](https://images.zenhubusercontent.com/61e1d30ba11212a19f0fe0d9/89d0efeb-dd85-45c7-86d8-600ebef6cd5d)
