### ISSUE TITLE
login page text is not customized   

### ISSUE THREAD

**Issue by amanthakur** [opensearch-project/security-dashboards-plugin#1101]
anyone can me tell me how i can customize login page text in [OpenSearch]

@opensearch-ci-bot

**Comment by amanthakur** [comment]
@kavilla can you give me the path of security dashboards plugin.

**Comment by RyanL1997** [comment]
Thanks for opening this, we will have one look at it.

**Comment by scrawfor99** [comment]
I will take a look at this and get back to you @amanthakur.

**Comment by scrawfor99** [comment]
Hi @amanthakur, 

I was able to gather some resources that may be helpful: 

https://opensearch.org/docs/latest/dashboards/branding/ -- Dashboards branding tutorial
https://github.com/opensearch-project/OpenSearch-Dashboards -- Dashboards github repo 

Right now, I do not believe it is possible to directly modify the login page style setting with the opensearch_dashboards.yml file; however it is still an option to modify the HTML/CSS options in order to place your company's logo above the login. 

If you would like further support for modifying the login page, please fill out a feature request by going to Issues>Feature Request and filling out the form. Likewise any contributions to this point would be welcome.

**Comment by RyanL1997** [comment]
Hi @amanthakur,

I think we do support the customization of basic auth's login button style and branding image for current version. You can modifying these by adding the feature flags of: 
`opensearch_security.ui.basicauth.login.buttonstyle` and `opensearch_security.ui.basicauth.login.brandimage`

In addition, there is a feature PR [https://github.com/opensearch-project/security-dashboards-plugin/pull/1110](url). We are currently working on this right now and it includes the support of those style customization for external authentication methods, such as OIDC and SAML.

**Comment by amanthakur** [comment]
@RyanL1997 @scrawfor99  I have changed it.  you can find the text running this command  ( grep -rnw / -e 'OpenSearch Dashboards' )  and there is file that name is **index.js** where you can change it .  :)
