### ISSUE TITLE
[FEATURE]Enable Anonymous Login along with OIDC Authentication in Multiple Authentication Mode

### ISSUE THREAD

**Issue by aoguan1990** [opensearch-project/security-dashboards-plugin#1124]
**Is your feature request related to a problem?**
[#74](https://github.com/opensearch-project/dashboards-anywhere/issues/74)

**What solution would you like?**
User Experience:
1. Single Authentication Mode:
- User is redirected to Login as Anonymous User for the first time login
- User is redirected to Login Page after Anonymous User log out
- User can choose to login as a regular user from Login Page

2. Multiple Authentication Mode:
- User is redirected to Login as Anonymous User for the first time login
- User is redirected to Login Page after Anonymous User log out
- User can login with preferred authentication option, like OIDC, SAML, Basic and Anonymous

This issue is addressed along with [PR #1110](https://github.com/opensearch-project/security-dashboards-plugin/pull/1110)

**Comment by RyanL1997** [comment]
Hi, @aoguan1990. Thank you for this feature suggestion!

As additional information, the reason to add this feature:

For the current behavior of security dashboard plugin, if we enable the anonymous login by adding the feature flag, it will skip the basic auth login page and directly access into the home page of dashboard. However, if the user logout as the anonymous user, the current design will bring user back to the basic auth login page, which has no option for anonymous login.

The expected behavior should be support the option of login as anonymous user at basic auth login page when anonymous feature is enabled.

**Comment by cliu123** [comment]
What happens with this issue - When anonymous auth is enabled, logout redirects to basic auth login page, so anonymous user cannot log in anymore.

**Comment by aoguan1990** [comment]
> What happens with this issue - When anonymous auth is enabled, logout redirects to basic auth login page, so anonymous user cannot log in anymore.

For single basic authentication mode with anonymous enabled, if anonymous user logout, the only way to login back with Anonymous user is to access OpenSearch Dashboards from a new window or browser. Otherwise, only basic login with valid username and password is required.

**Comment by aoguan1990** [comment]
This issue is addressed by PR #1110. So closed this issue.
