### ISSUE TITLE
Failed to initialize the plugin with an external OpenId provider

### ISSUE THREAD

**Issue by rfavreau** [opensearch-project/security-dashboards-plugin#114]
Hello,

I opened this issue because i can't initialize correctly the opendistro_security plugin with an external OpenId provider of my network.

![image](https://user-images.githubusercontent.com/22869037/69476171-c48da100-0dd6-11ea-862e-a7eaec764923.png)

### **Description**
Under CentOs, i installed Open Distro for Elasticsearch 1.2.1 (Elasticsearch and Kibana) into my personal network.
Elasticsearch and Kibana are configured to use OpenID Connect for the authentication process. The OpenId provider is external of my network: it's Microsoft Azure.
All works correctly: I am able to use my microsoft account for the authentication and open a session into Kibana.

So why open this ticket? ;-)

I did the same configuration but into my business network. In this case, during the startup of Kibana, I get the error message :
`[plugin:opendistro_security@7.2.1] Status changed from yellow to red - An error occurred during initialisation, please check the log`
The main difference between my personal network and my business network is the Internet access:

- My personal network : The server can access directy to Internet.

- My business network : To access to Internet, i need to use a HTTP proxy.

### **Issue**
Into kibana.yml, the url of my provider is:
`opendistro_security.openid.connect_url: "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555/v2.0/.well-known/openid-configuration"`

I didn't find properties into Kibana plugin to set an HTTP proxy. 

**How can use Kibana and opendistro_security plugin to use an external openId provider when the server hosting 'Open Distro for Elasticsearch" has not access directly to internet?**

Thanks for your contributions.
Richard.

**Comment by KiteAtao** [comment]
The opendistro_security plugin failed to initialize because during the startup of the plugin, the `opendistro_security.openid.connect_url` url is called to get endpoints urls.

- **lib/auth/types/openid/OpenId.js**
![image](https://user-images.githubusercontent.com/22869037/69499678-f85ee880-0ef4-11ea-86ef-194774b2a5de.png)

To implement an HTTP proxy with the object `Wreck`, it's necessary to use the module `https-proxy-agent`:
![image](https://user-images.githubusercontent.com/22869037/69499747-d87bf480-0ef5-11ea-97ab-3c4e7c0f098b.png)

With this update, the opendistro_security plugin starts correctly but when you want authenticate, you get a new error message.
During the authentication process, kibana calls the endpoints initialized during the startup and once again the object `Wreck` can not acces the Internet directly.

To resolve this new issue, i should update the file 'node_modules/bell/lib/oauth.js' with the same fix.

At the end, my Kibana with my external OpenId provider on my business network works correctly but these update are not acceptable to a 'true' solution.

**Comment by davidkarlsen** [comment]
We have the same problem, opensearch-dashboards fails when it attempts to lookup the OIDC discovery endpoint. Could a fix be added perhaps?

**Comment by sastorsl** [comment]
@zengyan-amazon do you think this is something you can look into?
Re: `server/auth/types/openid/routes.ts`

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
