### ISSUE TITLE
[BUG] UI is not reflecting the correct Mapped Users

### ISSUE THREAD

**Issue by devardee** [opensearch-project/security-dashboards-plugin#1188]
**What is the bug?**
When we create user and map roles using API, role mapping is not reflected in UI of "Mapped Users" section.

**How can one reproduce the bug?**

* Create a internal user using API. I have used below API call to create an internal user.

```
PUT _plugins/_security/api/internalusers/nikhil2
{
  "password": "xxxxxxxx",
  "opendistro_security_roles": ["all_access"]
}
Output:
{
  "status" : "CREATED",
  "message" : "'nikhil2' created."
}
```
*  Go to Security -> Internal Users and you will be able to see that user has been created.

* Now go to Security -> Roles -> all_access and you will find that the newly created user is not mapped to "all_access" role in "Mapped Users" section. I am attaching screenshot for your reference.

However when you describe the user using below API call, you can see that "all_access" is mapped to user and user will be able to perform all actions on the domain.

```
GET _plugins/_security/api/internalusers/nikhil2

Output:
{
  "nikhil2" : {
    "hash" : "",
    "reserved" : false,
    "hidden" : false,
    "backend_roles" : [ ],
    "attributes" : { },
    "opendistro_security_roles" : [
      "all_access"
    ],
    "static" : false
  }
}
```
**What is the expected behavior?**
Security -> Roles -> all_access should show all the users mapped to a role

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

![Mapped_Users_Bug](https://user-images.githubusercontent.com/80896069/199697758-76a6d763-def3-4aff-b4ae-d264626e60cd.png)

**Comment by peternied** [comment]
[Triage] @RyanL1997 Can you look into this issue to see what the scenario is, technically this looks correct, however this behavior is confusing to users.

@shanilpa Can you look into how we want to support these scenarios?

**Comment by devardee** [comment]
@peternied , I would also like to contribute on this

**Comment by RyanL1997** [comment]
Hi @devardee, thanks for filling this issue. Here are some outputs from my side according to the reproduction of this issue:
1. By running the following I created a internal user without specifying the `opendistro_security_roles`:
```
PUT _plugins/_security/api/internalusers/test01
{
  "password": "password"
}
```
2. And then I run this following commands to create a roles mapping for `all_access`:
```
PUT _plugins/_security/api/rolesmapping/all_access
{
  "users" : [ "admin", "test01" ]
}
```
3. I went to the `Security`>`Roles`>`all_access` to check the mapping I just created and it works.(see the following screenshot)
<img width="1043" alt="Screenshot 2022-11-16 at 12 24 54 PM" src="https://user-images.githubusercontent.com/109499885/202252751-dfcd950b-338f-44cb-8aca-186f4774c0b1.png">

4. However, back to the `Dev Tools`, when I did the API call to check the internal user I just created:
```
GET _plugins/_security/api/internalusers/test01

Output:
{
  "test01" : {
    "hash" : "",
    "reserved" : false,
    "hidden" : false,
    "backend_roles" : [ ],
    "attributes" : { },
    "opendistro_security_roles" : [ ],
    "static" : false
  }
}
```
As you can see even the roles mapping shows correct in the panel in step 3., the `opendistro_security_roles` in step 4. is still empty. I think this may relate to the issue here: https://github.com/opensearch-project/security/issues/2058. I will do more investigation on this and update with you again.

**Comment by davidlago** [comment]
Closing as expected behavior, please re-open with more details if that is not the case.
