### ISSUE TITLE
Put security_tenant query parameter on all URLs

### ISSUE THREAD

**Issue by shawnz** [opensearch-project/security-dashboards-plugin#123]
Hi there, this issue is more of a feature request than a bug. When the "Share" link is used, a URL is produced that specifies the tenant name in a query parameter so that the URL can be used regardless of the current tenant of the user who clicks it. However I think it would be convenient if all pages on Kibana always included the query parameter rather than just the share links. This would be helpful mainly for two reasons:

- Bookmarks to Kibana pages and other Kibana tabs open in the background would continue to work even if you switch tenants.

- Some pages don't have "Share" links, like for example the "View surrounding documents" page. Such a change would allow those pages to be shared just by copying the URL like you'd expect.

Thanks for reading and also thank you for all your work on this project.

**Comment by shawnz** [comment]
Another annoyance that is related to this issue is that links in the "recent items" pane will be broken if they point to items in a different tenant than you're currently in.

**Comment by micha558** [comment]
+1 for this feature request. We have many users which are sharing links by copying it out of their browsers. And we have many dashboards which are present in each tenant with the same id. So many users get data from other tenants that they expect.

**Comment by jgough** [comment]
I think this may be a necessity to fix #1203 and #1205 rather than just a feature request.  The current tenant implementation seems very broken for anything other than extremely simple access.

When accessing Dashboards with multiple tabs, or when sharing links to multiple tenants it is almost unusable as you often end up in the wrong tenant.  I'm afraid to say it's my number 1 frustration with Dashboards!

**Comment by davidlago** [comment]
Closing as this has been resolved (alongside #1012)
