### ISSUE TITLE
[BUG] Dashboard login problem - global_tenant getting displayed in custom tenants if Global tenant is disabled

### ISSUE THREAD

**Issue by deepak-rsystems** [opensearch-project/security-dashboards-plugin#1248]
**What is the bug?**
Dashboard login has a problem that if we give access to global_tenant for some user/role, then global_tenant is getting displayed in custom tenants if Global tenant is disabled.

**How can one reproduce the bug?**
Pre-requisites:

1. We have a custom tenant "cadm"
2. We have disabled "Global" and "Private" tenants

1. Go to Dashboard
2. Click on Single Sign-on
3. See that user is logged in to global_tenant by default:
<img width="735" alt="global-tenant-issue-1" src="https://user-images.githubusercontent.com/60732633/206370437-0689cd5d-363d-4340-b3af-fa0dfdfe3ab0.PNG">

4. Once the user selects the custom tenant "cadm", then the global_tenant automatically gets removed from custom tenant drop down:
<img width="747" alt="global-tenant-issue-2" src="https://user-images.githubusercontent.com/60732633/206370653-f0a68fd3-e543-40e5-afa7-d7b1e5f73045.PNG">

**What is the expected behavior?**
We should not see global_tenant in custom tenants drop down if Global tenant is disabled from multi tenancy configuration.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Opensearch version 2.4.0

**Comment by cwperks** [comment]
[Triage] @deepak-rsystems Thank you for filing this issue. We would gladly accept a PR.

**Comment by RyanL1997** [comment]
@deepak-rsystems Thanks for filing this issue, and I have reproduced this behavior and there will be a fix or further information provided soon.

**Comment by RyanL1997** [comment]
Update: I have confirmed with @cliu123 that this is a expected behavior. If the user has enabled multi-tenancy but disabled both 'Global' and 'Private' tenants, it will use this `global_tenant` as a temporary custom tenants before choosing/creating a custom tenants. Otherwise, it will make no difference with disabling multi-tenancy. If the user doesn't have any other custom tenant without `global_tenant`, it will return this error: 
`{"statusCode":400,"error":"Bad Request","message":"No available tenant for current user, please reach out to your system administrator"}`
However, for solve this confusion, I have implemented the above fix for user who has already have their own custom tenants so that this `global_tenant` label won't appear in the tenant selection list.
