### ISSUE TITLE
[Tracking] Replace legacy template with index template

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1385]
Coming from https://github.com/opensearch-project/security-dashboards-plugin/pull/1359

There are many backport branches this change was applied towards that are not about to be merged.

### OpenDistro
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1373
  -  Unique to branch typescript failure
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1372

### 1.*
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1365
  - Root Cause: https://github.com/opensearch-project/security-dashboards-plugin/issues/1383
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1366
  - Root Cause: https://github.com/opensearch-project/security-dashboards-plugin/issues/1383
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1363
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1360
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1362

### 2.*
- 2.0 Missing?
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1364
   - Run integration tests failure security_entity_api.test.ts & multi_tenancy.test.ts
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1367
  - Run integration tests failure `Plugin "securityDashboards" is only compatible with OpenSearch Dashboards version "2.2.1", but used OpenSearch Dashboards version is "2.2.2"`
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1368
  - Run integration test failure security_entity_api.test.ts
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1369
  - Run integration test / cypress failure `Plugin "securityDashboards" is only compatible with OpenSearch Dashboards version "2.4.1", but used OpenSearch Dashboards version is "2.4.2".`
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1370
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1371
  - Run Cypress tests failure, server didn't start
  - Run integration tests failure, saml_auth.test.ts, security_entity_api.test.ts
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1361

**Comment by peternied** [comment]
I've created an issue to address the mismatched branch protection rules, some of these pull requests might be impacted until they can be resolved.  Please @mention me if any PRs have all passing CI checks, and only blocked because of these rules and I'll help out.

- https://github.com/opensearch-project/security-dashboards-plugin/issues/1387

**Comment by cliu123** [comment]
@davidlago @peternied I've summarized why each branch CI fails. Would you mind helping resolve these blockers or lifting the blockers on the branches that could not be fixed? Otherwise, would you please suggest path forward on these backports? Thanks for the strong support to move these PRs forward!

- 2.6, 2.3, 2.1 fail as the security plugin artifact is not updated in [Maven repo](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-security/):

![Screen Shot 2023-03-23 at 9 41 02 AM](https://user-images.githubusercontent.com/16925774/227274057-d5cf9496-2959-4366-a531-0210e33bd799.png)

```
2023-03-06T22:36:27.4618478Z   ● start OpenSearch Dashboards server › create/get/update/list/delete internal user
2023-03-06T22:36:27.4618749Z 
2023-03-06T22:36:27.4619341Z     ResponseError: security_exception: [security_exception] Reason: no permissions for [indices:admin/index_template/put] and User [name=kibanaserver, backend_roles=[], requestedTenant=null]
```

- 2.4, 2.2 fail as Opensearch Dashboards version has not been bumped to `2.4.2`, so it does not match with the OSD core version in 2.4.

```
    Failed to initialize plugins:
    	Plugin "securityDashboards" is only compatible with OpenSearch Dashboards version "2.4.1", but used OpenSearch Dashboards version is "2.4.2". (incompatible-version, /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/plugins/security-dashboards-plugin/opensearch_dashboards.json)
```
```
ailed to initialize plugins:
2023-03-06T22:26:54.0499961Z     	Plugin "securityDashboards" is only compatible with OpenSearch Dashboards version "2.2.1", but used OpenSearch Dashboards version is "2.2.2". (incompatible-version, /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/plugins/security-dashboards-plugin/opensearch_dashboards.json)
```

- 1.3 fails on downloading security plugin artifact:

```
2023-03-09T14:54:49.1101231Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact org.opensearch.plugin:opensearch-security:zip:1.3.9.0-SNAPSHOT in temp (https://aws.oss.sonatype.org/content/repositories/snapshots/)
```

- opendistro-1.11:

looks like @peternied has identified a potential fix: https://github.com/opensearch-project/security-dashboards-plugin/pull/1373#issuecomment-1480316209

- 1.1, 1.0 have been failed for a while, and is not fixable:

https://github.com/opensearch-project/security-dashboards-plugin/actions?query=branch%3A1.1
https://github.com/opensearch-project/security-dashboards-plugin/actions?query=branch%3A1.0

**Comment by peternied** [comment]
Haven't seen any work on these changes in a considerable amount of time, looks like this request is no longer need.  Please reopen if this isn't the case.
