### ISSUE TITLE
[BUG] Changes to show rows number are not peristent in current session

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security-dashboards-plugin#1388]
**What is the bug?**
When you go to the Roles page of the Security Dashboards, you will be shown 10 roles. On the bottom left of the page, you can swap this to show more i.e. 50. If you make this swap, you will see 50 roles. However, if you then click a different tab (without logging out of the current user) and come back, you will once again only see 10 roles. Perhaps this is expected, but I assume this should be persistent within the same session. 

**How to Reproduce**
1. Spin up an OpenSearch cluster with Security installed and Dashboards. 
2. Use the default credentials to login
3. Go to the Roles page of the Security tab
4. Scroll to the bottom of the page and change the number of row visible to a number other than 10 
5. Click a different page in the Security plugin 
6. Return to the roles page
7. You should now see only 10 roles again. 

**Expected Behavior**
I assume the "Roles per page" setting should persist within the same session. Perhaps this is not the case.  

**What is your host/environment?**
 - Version 2.6.0
 - Plugins Security

**Comment by derek-ho** [comment]
This can probably be done via session storage. Is there any other attributes it makes sense to persist across the session?

**Comment by scrawfor99** [comment]
> 

Hi @derek-ho, I am not sure about other values in general, but I would say this is a good example of something that should be persisted.

**Comment by RyanL1997** [comment]
Add some input here: I think this is from the original design of the pagination from `Eui`/`Oui` 's `In-memory table` /  `Basic table`. I think this may not be changed, since this same element are also used in different plugins + dashboard core, and the behavior is the same - the pagination will not be stored in the session storage. 

However, I don't know if we can change this behavior by changing the logic of `onTableChange` callback

### Reference
EUI: https://eui.elastic.co/pr_3350/#/tabular-content/in-memory-tables
OUI: https://oui.opensearch.org/1.5/#/tabular-content/in-memory-tables

**Comment by derek-ho** [comment]
Yes, I agree @RyanL1997 closing this as I don't think its worth the effort. There is no precedence for this in the dashboard ecosystem. One alternative @scrawfor99 if you are very insistent on this feel free to re-open - we would need to add a section to http://localhost:5601/app/management/opensearch-dashboards/settings
to persist this change across the security plugin.
