### ISSUE TITLE
[BUG] yarn build is not working on Windows

### ISSUE THREAD

**Issue by nurbq** [opensearch-project/security-dashboards-plugin#1390]
**What is the bug?**
When trying to run command "yarn build" command on Windows it shows: error Command failed with exit code 1,
rename build/securityDashboards-3.0.0.zip to build/security-dashboards-3.0.0.0.zip
'mv' is not recognized as an internal or external command.
Even when I tried running "yarn build --inline-builds --windows"

**How can one reproduce the bug?**
1. Go to \OpenSearch-Dashboards\plugins\security-dashboards-plugin
2. Run "yarn build" or "yarn build --inline-builds --windows" on terminal

**What is your host/environment?**
 - OS: Windows

**Do you have any screenshots?**

![Screenshot 2023-03-30 230955](https://user-images.githubusercontent.com/106753054/228926463-8bc84621-69c0-40ed-b212-523b046b6d64.png)
![Screenshot 2023-03-30 231029](https://user-images.githubusercontent.com/106753054/228926442-4b6062b6-3251-40a9-8a57-65501f11756c.png)

**Comment by cwperks** [comment]
Hi @nurbq , thank you for filing this issue. It looks like the error is coming from this line: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/build_tools/rename_zip.js#L26 where the `mv` command is not defined on your platform.

Is it possible to use `fs` here?

```
const fs = require('fs');
fs.renameSync(oldPath, newPath);
```

This area must be missed by tests because it was not caught when running this repo's CI on windows. Would you try be able to try a platform agnostic command to move the zip file and verify `yarn build` and `yarn build --inline-builds --windows`?

**Comment by scrawfor99** [comment]
[Triage] Hi @nurbq, thank you for taking the time to file this issue. I understand that you and @DarshitChanpura are taking care of this issue, so I will be assigning you both to it.

**Comment by nurbq** [comment]
@cwperks Thanks, it worked.

**Comment by peternied** [comment]
@nurbq Sounds like you were able to work around the issue, is this something that you could fix with a pull request?

**Comment by nurbq** [comment]
Yes, I am doing it

**Comment by davidlago** [comment]
Checking in, as #1393 got merged... closing this one, please reopen if not the case.
