### ISSUE TITLE
Kerberos auth is partially broken

### ISSUE THREAD

**Issue by dpotapov** [opensearch-project/security-dashboards-plugin#140]
Reposting the issue here from [forums](https://discuss.opendistrocommunity.dev/t/kibana-kerberos-auth-is-broken-in-1-4-0/2198), because my investigation shows there is a degradation with Kerberos support in Kibana.
I’ve upgraded my OpenDistro ES + Kibana setup from 1.1.0 to 1.4.0 and noticed that querying data in Kibana no longer works:

* https://elastic-server/_opendistro/_security/authinfo - **WORKS**
* https://kibana-server/app/security-accountinfo - **WORKS**, shows my username and roles
* https://kibana-server/app/kibana#/discover - **NOT WORKING**

![image](https://user-images.githubusercontent.com/5475708/74453049-7de49b80-4e47-11ea-857b-44c846a38a63.png)

Digging into HTTP packets between Kibana and Elasticsearch shows:

```
Authentication Exception :: {"path":"/_msearch","query":{"rest_total_hits_as_int":"true","ignore_throttled":"true"},"body":"{\"index\":\"jira\",\"ignore_unavailable\":true,\"preference\":1581456941567}\n{\"timeout\":\"30000ms\",\"version\":true,\"size\":500,\"sort\":[{\"date\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}}],\"_source\":{\"excludes\":[]},\"aggs\":{\"2\":{\"date_histogram\":{\"field\":\"date\",\"fixed_interval\":\"30m\",\"time_zone\":\"America/Chicago\",\"min_doc_count\":1}}},\"stored_fields\":[\"*\"],\"script_fields\":{},\"docvalue_fields\":[{\"field\":\"Created\",\"format\":\"date_time\"},{\"field\":\"Resolved\",\"format\":\"date_time\"},{\"field\":\"Updated\",\"format\":\"date_time\"},{\"field\":\"created date\",\"format\":\"date_time\"},{\"field\":\"date\",\"format\":\"date_time\"},{\"field\":\"resolution date\",\"format\":\"date_time\"},{\"field\":\"updated date\",\"format\":\"date_time\"}],\"query\":{\"bool\":{\"must\":[],\"filter\":[{\"match_all\":{}},{\"range\":{\"date\":{\"format\":\"strict_date_optional_time\",\"gte\":\"2020-02-10T21:37:37.460Z\",\"lte\":\"2020-02-11T21:37:37.460Z\"}}}],\"should\":[],\"must_not\":[]}},\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}},\"fragment_size\":2147483647}}\n","statusCode":401,"response":"{\"error\":{\"header\":{\"WWW-Authenticate\":\"Negotiate\"}}}","wwwAuthenticateDirective":"Negotiate"}
        at respond (/usr/s hare/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
        at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
        at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
        at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)
        at IncomingMessage.emit (events.js:194:15)
        at endReadableNT (_stream_readable.js:1103:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```
so the important part here is:

```
"statusCode":401,"response":"{\"error\":{\"header\":{\"WWW-Authenticate\":\"Negotiate\"}}}","wwwAuthenticateDirective":"Negotiate"}
```

It seems Kibana does not forward "Authorization" header to Elastic in some cases.

**Comment by trexx** [comment]
FWIW, I am also seeing this issue with 1.6.0.0. Did you or anyone else figure this out?

**Comment by trexx** [comment]
Looks like this is because requests proxied to elasticsearch through Kibana (via /elasticsearch) do not have an Authorization header when Kerberos has authenticated the connection.
Elasticsearch responds with a 401 `{"error":{"header":{"WWW-Authenticate":"Negotiate"}}}` however Kibana proxies the response back to the client with a "200 OK" preventing our clients from re-authenticating with Kerberos. 

This works with basic authorization because the browser always sends the authorization header on each request. Because Kerberos authenticates the tcp connection not all requests have a authorization header and so this issue occurs.

**Comment by trexx** [comment]
Regarding version 1.6.0.0:
Looks like this is because requests proxied to elasticsearch through Kibana (via /elasticsearch) do not have an Authorization header when Kerberos has authenticated the connection.
Elasticsearch responds with a 401 `{"error":{"header":{"WWW-Authenticate":"Negotiate"}}}` however Kibana proxies the response back to the client with a "200 OK" preventing our clients from re-authenticating with Kerberos. 

This works with basic authorization because the browser always sends the authorization header on each request. Because Kerberos authenticates the tcp connection not all requests have a authorization header and so this issue occurs.

If Kibana responded with a 401 instead of the 200, then our clients would negotiate kerberos.

**Comment by micheljung** [comment]
So is Kerberos for Kibana supported or not? We've configured Elasticsearch according to the documentation and get the `Authentication: Negotiate` challenge when accessing Elasticsearch. Kibana, however, still brings up the login form and no Authentication header is sent to the browser.

Also, the Kibana chapters in the documentation don't mention Kerberos at all.

 @seraphjiang can you confirm?

**Comment by trexx** [comment]
Looks like since the refactoring of the Kibana plugin, Kerberos was removed as an authentication type.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
