### ISSUE TITLE
Tenant Migration process w/ bad Index name generation

### ISSUE THREAD

**Issue by francisco-hoo** [opensearch-project/security-dashboards-plugin#141]
Hi guys,

I've tried to understand exactly _when_ and _how_ tenant migration occurs, but without success. Every time kibana restarts, the migration starts. Although, the _"reindex"_ and _"migrate"_ process can't handle some indices names that ends with numbers. For example:

If we create a tenant named **bug48** (which ends with numbers):
`PUT _opendistro/_security/api/tenants/bug48
{
  "description": "Cool."
}`

An index named `.kibana_94091256_bug48` will be generated, and if i try to restart kibana, this what gonna happens:

```
[info][migrations] Creating index .kibana_94091256_bug48_50.
[info][migrations] Reindexing .kibana_94091256_bug48 to .kibana_94091256_bug48_49
[info][migrations] Migrating .kibana_94091256_bug48_49 saved objects to .kibana_94091256_bug48_50
[info][migrations] Pointing alias .kibana_94091256_bug48 to .kibana_94091256_bug48_50.
[info][migrations] Finished in 519ms.
```

As you can see, the script thinks the version of the migration is 50 (_50) and not the first one (_1). Another question: why do we have this middle migration version index (_49)?

This process should be documented or more explained to the community, because it may bring some problems like shards allocation, disk space. Image if we have 20 Tenants and 50 users, at the end we gonna have 140 (20*2+50*2) indices and consequently shards.

**Comment by yuxitang-amzn** [comment]
Every tenant is a standard kibana index (same as .kibana). This plugin relies on kibana to migrate tenant indices. They share the same process with how kibana migrate .kibana index. 

For naming:
The kibana takes the ending number (see [code](https://github.com/elastic/kibana/blob/3cef292bbd52edb94d87ec73401553e8450a8736/src/core/server/saved_objects/migrations/core/migration_context.ts#L186) as version number). And reindex (clone) to version+1, then migrate to version+2. The same process applies to kibana index even without this plugin, if you change your default kibana index to `.kibana_bug48` and upon kibana start you could see it migrates to `.kibana_bug49`.

Why migrate:
Since kibana 6.5, it will trigger an migration process if the kibana index is not aliased ([ref](https://www.elastic.co/guide/en/kibana/current/upgrade-migrations.html). The tenant index is not created with alias, so it need to be aliased next time kibana restart. But the same index should not migrate again if you don't upgrade kibana.

**Comment by davidlago** [comment]
It seems like this question has been resolved, closing issue. Please re-open with additional questions if needed. Thanks!
