### ISSUE TITLE
[Flaky CI] Intermittent failures with Cypress

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#1599]
In recent CI runs, there were flaky failures observed which went away on subsequent retries. Here is the failure log:
```console
Cypress failed to make a connection to Firefox.

This usually indicates there was a problem opening the Firefox browser.

Error: could not find CRI target
    at lazyAssLogic (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
    at findStartPage (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

error Command failed with exit code 1.
```
And here is a recent build output: https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/6395013515/job/17357702336?pr=1580

Expected outcome:

1. Analyze whether this is a bug on our end or from cypress side.
2. Implement a fix.

**Comment by DarshitChanpura** [comment]
Seems like an issue from cypress side: https://github.com/cypress-io/cypress/issues/6518

**Comment by scrawfor99** [comment]
[Triage] Hi @DarshitChanpura, thank you for filing this issue. We can still have someone confirm this and then close. Thank you.

**Comment by cwperks** [comment]
https://github.com/opensearch-project/security-dashboards-plugin/pull/1728 will resolve the error seen in the OP of this issue. The tests will now run with Chrome instead of FireFox.

The tests are currently only running on the `ubuntu-latest` runners and will need to be re-enabled on windows. The windows CI is unstable as a result of slow runners that run out of disk space after installing OSD. There is a separate issue around support for Windows so I will close this issue as the OP is resolved: https://github.com/opensearch-project/security-dashboards-plugin/issues/1666
