### ISSUE TITLE
Hide applications for some users

### ISSUE THREAD

**Issue by remioo** [opensearch-project/security-dashboards-plugin#160]
It would be good to be able to hide some items in the left sidebar for specific users. 
I don’t want to see e.g the dev tools or index management for my basic users, while it should be available for more advanced ones

Basically like the Space privileges in xpack

**Comment by francisco-hoo** [comment]
I've started develop this feature, based on user roles. 
So basically it's a plugin that integrates with some functions and endpoints of Open Distro Security to map roles with couple of allowed apps. 

It should be interesting if we can integrate this with Open Distro Security for Kibana.

**Comment by daskanu** [comment]
I also would appreciate this feature, because I don't want to receive tickets from my users why they can't create alerts or set up index management although they see the icons.

**Comment by pfinken-synergy** [comment]
@francisco-hoo I have similar needs but I would like to completely remove some navigation items for all users. I want to keep only discover, visualizations and dashboard.

Is this achievable with a plugin?

**Comment by everlytics** [comment]
**francisco-hoo says:**
>So basically it's a plugin that integrates with some functions and endpoints of Open Distro Security to map roles with couple of allowed apps.

This is going to be a fair amount of development effort I believe. Please let me know once you have it ready. I'm also looking for something like this. X-Pack has it and it is part of built-in Security framework.

But I still wonder if it is achievable with a plugin. Wouldn't it be risky fiddling with Open Distro's Security framework?

**Comment by francisco-hoo** [comment]
Due to the changes in Kibana source code from 7.0.1 to 7.6.1, the development of this feature needs a little bit more effort.
Some changes in code are not documented by Kibana, so I've digging on the source code to find the best solution, basically the `server.getUiNavLinks()` was deprecated. Based on that I need to find another way to discover which apps (`NavLinks`) are _disabled_ and/or _hidden_ (`_disabled, _hidden`).

The only thing that I've found is related to[`ui/chrome` (front-end part)](https://github.com/elastic/kibana/issues/20696)

I would like to share some prints of what I've done till now.. let me finish some things first guys

**Comment by drlight17** [comment]
I've recently done a hack type plugin for Kibana to hide some menu elements from users with no rights to Security section. There are also a few fixes to UI. It's a frontend plugin (some jquery +some css). Placed it [here](https://github.com/drlight17/kibana-menu-hide). Maybe someone will find it userful.

**Comment by sergiospa** [comment]
Hi all,
Are there any updates on this? It would be quite interesting to hide applications where a user can't access rather than accessing and getting a lot of errors. Any estimated time for this feature to be available?

Thanks!

**Comment by davidlago** [comment]
Conversation continues here https://github.com/opensearch-project/security/issues/2701, closing this one.
