### ISSUE TITLE
[BUG-2.11] UI prompts tenant selection at every first login

### ISSUE THREAD

**Issue by hengirmen** [opensearch-project/security-dashboards-plugin#1717]
**What is the bug?**

- Whenever the OpenSearch Dashboards UI is accessed on a new machine "Select your tenant" window pops up, even though multi-tenancy is **disabled**. We don't want the customers and common users to see this prompt since it could be confusing.

- Also, when the multi-tenancy is **enabled** and default tenant is set to "Private", UI still prompts tenant selection.

**How can one reproduce the bug?**
1. Open OpenSearch Dashboards UI in a browser.
2. Log in with user credentials.
3. UI prompts the user to select the tenant.

**What is the expected behavior?**

- When multi-tenancy is **disabled**, we expect the users to access the dashboards directly without facing this prompt.

- Also when the multi-tenancy is **enabled** and a default tenant is set, we don't want the users to see the tenant selection window.

**Do you have any screenshots?**
Figure 1: Multi-tenancy is **disabled**, yet the prompt to set tenants still pops up.
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/98303149/c74ae4a7-ddf2-4ece-a663-fd2017c794ed)

Figure 2: Multi-tenancy is **enabled**, default tenant is set, yet the prompt pops up with every first login.
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/98303149/09f6707e-aa96-4add-9736-eb70570bad84)

**Comment by hengirmen** [comment]
Hi @scrawfor99 , thanks for the response. Any updates yet?

**Comment by peternied** [comment]
Thanks for checking in @hengirmen, my team is entering it a new sprint next week and I've earmarked this issue for that list.  More updates forthcoming...

**Comment by wbeckler** [comment]
Will this be backported into prior versions that include the bug? Also, what is the workaround for someone who has security enabled and wants to suppress the popup? Is it enough to map a role to a default tenant?

**Comment by cwperks** [comment]
@wbeckler There is no planned patch releases for any of the impacted branches so while it can be backported to those branches, it would never be officially released. This bug impacts versions 2.7, 2.8, 2.9, 2.10 and 2.11. 

The workaround is to disable multi-tenancy through `opensearch_dashboards.yml` instead of disabling through the UI dynamically.

```
> opensearch_dashboards.yml

opensearch_security.multitenancy.enabled: false
```

Please not that this settings acts as a feature flag and to re-enable multi-tenancy would require a reboot of OSD. When this setting is set to false, you cannot enable multi-tenancy through the Security pages in OSD.

<img width="1904" alt="Screenshot 2024-02-01 at 9 45 43 AM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/17432265/68e6c8e8-c681-4ed1-a8e2-9ddab9420690">

**Comment by wbeckler** [comment]
Can this be backported to at least 2.11, so that future patches will include that fix?

**Comment by DarshitChanpura** [comment]
@wbeckler the change is ready to be backported to 2.11: https://github.com/opensearch-project/security-dashboards-plugin/pull/1765

**Comment by cwperks** [comment]
> Is there a planned patch release for 2.11.1

2.11.1 is already released. There is no current plan for 2.11.2. Generally only security fixes are included for patch releases.

**Comment by DarshitChanpura** [comment]
oops.. I meant 2.11.2

**Comment by davidlago** [comment]
Once 2.12 goes out, there will not be 2.11 patches anyway.

**Comment by DarshitChanpura** [comment]
In that case I will close: https://github.com/opensearch-project/security-dashboards-plugin/pull/1765
