### ISSUE TITLE
[BUG] Tenant Tab behavior when Local Cluster is disabled

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1933]
**What is the bug?**
When local cluster is disabled, the "tenant" tab is still pulling info from the local cluster - this is because this tab is locked to the local cluster even when there are external clusters due to dashboards confusion - this needs to be addressed - either show empty data on this tab or remove the tab altogether when local cluster is disabled.

**Comment by derek-ho** [comment]
@kgcreative can you add any comments here on what is the expected behavior here?

**Comment by kgcreative** [comment]
This is not a bug and is as intended. The local cluster being disabled means we don't want to use the indexes on the local cluster for data analysis, but the local cluster is the compute for OSD instead. We should probably omit the data source picker for multitenancy in general, since it's OSD multi tenancy, and not backend multitenancy

**Comment by derek-ho** [comment]
> This is not a bug and is as intended. The local cluster being disabled means we don't want to use the indexes on the local cluster for data analysis, but the local cluster is the compute for OSD instead. We should probably omit the data source picker for multitenancy in general, since it's OSD multi tenancy, and not backend multitenancy

Sure we can remove the picker from this tab overall. I get what you are saying, but I still think it is an edge case - when local cluster is hidden, the picker shows like this - an empty state, but it is still pulling data from the local cluster. @kgcreative so final call is to just remove the picker from this tab all together?
<img width="1271" alt="Screenshot 2024-04-30 at 12 43 14 PM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/e94b8460-70f0-4021-b0ab-e0e623d8d6d6">

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thanks for filing this issue. It looks like you opened a PR to resolve this and are working with Kevin to take the best approach for handling things. Going to marked as triaged.

**Comment by kgcreative** [comment]
Ideally we should show a read-only single-select state showing the local cluster (for consistency sake), rather than removing local cluster. I think we need to show local cluster in security regardless of whether the local cluster is disabled, since that's how that will allow customers to do things like setup auth, create users, roles, etc for opensearch dashboards when security is enabled.
