### ISSUE TITLE
[RFC] Run or transfer full FTR tests to security dashboards plugin repo

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1936]
**Is your feature request related to a problem?**
Recently there was an integration test failure that was caught only at release time. This is because we are not running the whole integration test suite on every PR (we seem to only be running a sub-set of them). We should either migrate all the tests over to run on our own CI for every PR, or we should add a workflow/add onto an existing workflow to run every test that the infra team will run during releases on every PR. 
**What solution would you like?**
See above
**What alternatives have you considered?**
None
**Do you have any additional context?**
None

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thank you for filing this issue. It sounds like this would help improve the testing infrastructure of the security repo and the project as a whole. I will mark this as RFC so that people can leave their thoughts and then we can go from there once there has been a ~2 week period for input.
