### ISSUE TITLE
[REQ] Switch Tenant UI Usability Improvements

### ISSUE THREAD

**Issue by apsivam** [opensearch-project/security-dashboards-plugin#615]
I would like to suggest some usability improvements for the new Switch tenant UI (>=1.10)

1. We have a bunch of tenants (~50) and selecting one for an admin user (have access to all tenants) is not really easy. Can this list be sorted so that it would be easier to select which one we want to switch to?

2. Can we bring back tenant name type ahead search?

3. Finally, Can we add an option to remember the selected tenant option in the future?

**Comment by AlexShuraits** [comment]
I would like to add one more suggestion:
Is to reduce the number of actions needed to switch tenant.
Currently, I need to do 4 actions:
- Click on the user icon to open the dropdown menu
- Choose "Switch tenant"
- Select tenant from the dropdown list
- Click confirm

This actually may be done with 2 actions:
- Choose "Switch tenant"
- Select tenant from the dropdown list

Since I am doing it quite often during the day, it became a bit annoying.

**Comment by oscarkraemer** [comment]
Regarding 3. I would also like to be able to set a "remember my choice" checkbox so that I don't need to choose a tenant every time I log in. Since I have ~20 tenants but mostly use one.

(Also the most 👍 issue in this project is related https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/74 )

**Comment by yuxitang-amzn** [comment]
@kgcreative Would you like to take a look at the suggestions and consider include in next release?

**Comment by yuxitang-amzn** [comment]
> We have a bunch of tenants (~50) and selecting one for an admin user (have access to all tenants) is not really easy. Can this list be sorted so that it would be easier to select which one we want to switch to?
Good advice, this will be easy.

> Can we bring back tenant name type ahead search?
It is a little bit complex since we are using `EuiSelect` component from EUI. It doesn't support a search functionality.

> Finally, Can we add an option to remember the selected tenant option in the future?
We have considered this before. The tech limit there is in previous version it has separate cookie key for auth and tenant, so after logout only clear the auth but keep the tenant. In kibana new plugin framework since 7.9, it only allows one cookie key, which means after logout it would be clear completely. Currently we are considering browser localStorage, while a security concern is that we can't use server side encryption for it so may expose to other user on the same host.

A workaround for now to quick navigate to a specific tenant is adding a bookmark in browser, by adding `?security_tenant={tenant name}` to the end of url. After login you can click the bookmark to switch to that tenant.

**Comment by yuxitang-amzn** [comment]
@apsivam @oscarkraemer 
We introduced an checkbox to remember selection in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/650. It has been merged into main branch and will be available in next release (probably 1.13). Alternatively you can also build from source.

I'll keep this issue open since sorting and searching is still in queue.

**Comment by alexbde** [comment]
Also, not to be forgotten from #519:

> the plan is to skip the tenant selection if there is only one tenant available for the user

**Comment by oscarkraemer** [comment]
I got some feedback from my users regarding the tenant selection menu.
1. It would be good if the admin would be able to easily customise the `Choose a custom` tenant text, for example through a variable in kibana.yml.
2. It would be nice if the tenant description could be visible in the `Choose from custom` drop down menu. Since the tenant name does not seem to descriptive enough.

**Comment by Hokwang** [comment]
@zengyan-amazon 
I decided not to use tenant feature. But the dialog shows when user first login.

There's nothing I can except click Cancel.

![image](https://user-images.githubusercontent.com/1247030/108796178-7ebc1b80-75cb-11eb-864a-6153385f1a54.png)

**Comment by fracoes** [comment]
@Hokwang this popup it's based on the value of a cookie (`opendistro::security::tenant::saved`). If the value is `null` the Open Distro Security for Kibana throws' the popup.

It's should be possible to disable this Pop-up by a parameter at `kibana.yml` and not only by this "hardcoded" cookie value.

**Comment by francisco-hoo** [comment]
@Hokwang this pop-up it's based on the value of a cookie (`opendistro::security::tenant::saved`). If the value is null the Open Distro Security for Kibana throws' the pop-up.

It's should be possible to disable this Pop-up by a parameter at `kibana.yml` and not only by this "hardcoded" cookie value.

**Comment by davidlago** [comment]
Tenant selection UI has been revamped in recent versions, closing this issue as it seems like the points brought up (ordering, remembering selection, typeahead) have been added.
