### ISSUE TITLE
Error 403 on Dashboards - Tenant Tenant_Name is not allowed to write (user: user1)

### ISSUE THREAD

**Issue by gferrette** [opensearch-project/security-dashboards-plugin#681]
Hello,

I'm using opendistro version 1.0.2 and i have configured a role with access to a Tenant with read-only permission (kibana_all_read), and sometimes the user gets an 403 error when accessing the dashboard, and the log messages is below:

Elasticsearch logs:
Tenant Tenant_Name is not allowed to write (user: user1)

Kibana logs:
Jan 19 09:48:51 server kibana: {"type":"response","@timestamp":"2021-01-19T12:48:51Z","tags":[],"pid":11719,"method":"post","statusCode":403,"req":{"url":"/api/kibana/settings","method":"post","headers":{"host":"server:5601","accept":"application/json"....

It seems that is sending an "POST /api/kibana/settings" with a read-only Tenant.

Is there any workaround for this?

Thanks in advance!

Gabriel.

**Comment by davidlago** [comment]
Hi Gabriel. Sorry for the late response here. Things have changed quite a bit since ODFE 1.0.2, I hope that this problem has been resolved for you since then. If that is not the case and this is somethign that is present in more recent versions of OpenSearch, please re-open with additional details and we'll look into it. Thanks!
