### ISSUE TITLE
opendistro_security.multitenancy.tenants.preferred is not taking effect 

### ISSUE THREAD

**Issue by pratikshavyas** [opensearch-project/security-dashboards-plugin#707]
I am using kibana security plugin 1.9.0 and have enabled multitenancy. Everything is working properly except opendistro_security.multitenancy.tenants.preferred is not having any effect on the ordering in the Tenants tab of Kibana. Even after configuring the parameter the list is coming in the default order.
Configuration in kibana.yml
        opendistro_security.multitenancy.enabled: true
        opendistro_security.multitenancy.enable_filter: true
        opendistro_security.multitenancy.tenants.preferred: ["Private","xyz","Global","abc"]
        elasticsearch.requestHeadersWhitelist: [ "Authorization", "securitytenant" ]
Please check and suggest.
Thanks in advance

**Comment by davidlago** [comment]
Is this still an issue? We have not received any other reports of this behavior and it has been a while, so not sure if you were able to get past this issue or is it still happening? Given the multiple changes since that (now) unsupported version, I'm going to close this one but please feel free to re-open if you need help. Thanks!
