### ISSUE TITLE
Unable to share dashboards with JWT authentication

### ISSUE THREAD

**Issue by jjmerchante** [opensearch-project/security-dashboards-plugin#712]
Hi!

We have a problem sharing the dashboards of users who are authenticated with JWT.

We are currently using Open Distro 1.6.0 to offer an authentication method for Kibana for multiple users. Authentication is done through JSON Web Token and each user has a role assigned with different permissions with DLS (Document Level Security).

The problem we have encountered is that when using the Kibana "Share" button, the URL does not incorporate the JWT, so when trying to access using that link, the following error appears:

![image](https://user-images.githubusercontent.com/10515012/81579385-65cfda00-93ac-11ea-93bf-62ef0981b2f0.png)

We have tried to find some solutions to the problem, investigating how Kibana constructs the URL that is copied to the clipboard when you click the "Share" button. These solutions involve modifying the Kibana code, but I think that here at Open Distro you do not make direct modifications to Kibana, and we are interested in continuing to use Open Distro for all the things it brings to our project.

Anyway, the possible solutions we propose to this problem would be the following:

* Save the token in the sessionStorage of the browser the first time a request is sent to Kibana. In this way, within the client code of the URL construction of the "Share" button, we can access that token and add it to the URL that is passed to the client.

* Modify the server side of Kibana so that when the request with the token arrives, it will be passed to the client.

I guess other people had this problem before, but we have not seen any related Issue. Do you have any suggestion to solve it?

Thank you!

**Comment by jsmanrique** [comment]
Any news about this?

**Comment by palashhedau** [comment]
Hi @jsmanrique May I know what url you get after you hit the share button? 

I know you are not getting the JWT token in the params, but I want to see what URL you get. 

I am checking if we store the authorization header value somewhere inside the session.

**Comment by jjmerchante** [comment]
Hi @palashhedau These are the URLs we get:

- **Snapshot**: https://cauldron.io/kibana/app/dashboards#/view/a834f080-41b1-11ea-a32a-715577273fe3?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-6M,to:now))&_a=(description:'This%20is%20a%20basic%20public%20dashboard%20for%20Cauldron%20analyzed%20projects%20projects',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Cauldron%20Public%20Dashboard',viewMode:view)

- **Saved object**: https://cauldron.io/kibana/app/dashboards#/view/a834f080-41b1-11ea-a32a-715577273fe3?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-6M%2Cto%3Anow))

You can test it by yourself at https://cauldron.io/project/1119/public-kibana , that URL redirects to kibana with a JWT token in the params

Thank you

**Comment by palashhedau** [comment]
Hi @jsmanrique,

By any chance did you test this scenario? 

User A generate the URL and gives it to User B.
User B is logged in and might have some DLS/FLS permission. User B uses the URL and is granted access. 
If User B is not logged in, they will get error `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`

What is the scenario for user B when it gets the error mentioned in the description? 

Because when I tried to generate snapshot link with user 1119, I tried to access it with user 1120(after login) and was successfully able to open page and view dashboard

**Comment by jjmerchante** [comment]
Hi @palashhedau,

Yes, that works. But if user B...
- is not authenticated, is unable to see anything (other than Unauthorized).
- is authenticated, is watching the shared visualization with different data. Which I think is incorrect, since user A is sharing a dashboard with some data that he wants B to see.

I think some kind of authentication or permissions needs to be included in the Kibana URL for it to work

**Comment by palashhedau** [comment]
- is not authenticated, is unable to see anything (other than Unauthorized).
   **This is a correct scenario, if user B is not authenticated by its own JWT, he should not have access to the url shared by user A.**

- is authenticated, is watching the shared visualization with different data. Which I think is incorrect, since user A is sharing a dashboard with some data that he wants B to see.
  **Will check on this**
