### ISSUE TITLE
Evaluating current tenant selection panel

### ISSUE THREAD

**Issue by yuxitang-amzn** [opensearch-project/security-dashboards-plugin#718]
This is the current tenant selection panel. We have adopt some requests from https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/615 that adding an option to save tenant selection and adding search/sort functions.

![image](https://user-images.githubusercontent.com/63078162/109369686-26e31600-7852-11eb-84a7-1131097900cb.png)

Any experience improvement?

**Comment by jimishs** [comment]
Could we remember the tenant choice implicitly without any user input (no checkbox needed)?

**Comment by yuxitang-amzn** [comment]
> Could we remember the tenant choice implicitly without any user input (no checkbox needed)?

Could you provide a reason for it?

**Comment by seanneumann** [comment]
Notes from discussion between PM and Eng...

1. Do we prompt users on very first login for tenant selection? *Yes*
2. Do we implicitly remember selection (aka do we remove the checkbox)? *Yes*
3. What is the default selection? *Private*

**Comment by arnitolog** [comment]
I can be wrong, but I think that this panel should be disabled in case we set `opendistro_security.multitenancy.enabled: false` Right now this panel appears on every login and breaks the ability to create reports.
Here is a panel that we see on each and every login:
![image](https://user-images.githubusercontent.com/34036079/109477336-92122f80-7a80-11eb-9d9d-b9064a22e4f6.png)
and here is how the report looks like:
![image](https://user-images.githubusercontent.com/34036079/109477375-9e968800-7a80-11eb-829e-f9e47236071e.png)

**Comment by jgough** [comment]
We have a system where each user only has access to one tenant.  For this we have disabled the global and private tenants.

If a user can only select one tenant in the UI then I feel that it would be reasonable to not present the user with a redundant tenant selection UI and take the user straight to the only tenant that they can access.

![image](https://user-images.githubusercontent.com/968442/115520920-8bcf5100-a282-11eb-87f7-6712d340af3d.png)

**Comment by jgough** [comment]
Are there any further thoughts on making improvements around the tenant selection box?  It seems to me that there are a lot of outstanding usability issues around this and I think there are some big wins that could be had here.

- Do not present tenant box if only one tenant is available to the user (as above) and https://github.com/opensearch-project/security-dashboards-plugin/issues/519
- Do not show tenant box if multitenancy is disabled https://github.com/opensearch-project/security-dashboards-plugin/issues/728
- Set a default tenant for a new user or role https://github.com/opensearch-project/security-dashboards-plugin/issues/679 https://github.com/opensearch-project/security-dashboards-plugin/issues/74
- Allow easier switching of tenants https://github.com/opensearch-project/security-dashboards-plugin/issues/103

**Comment by derek-diaz** [comment]
Here are some of thoughts on tenants:

- If a role has access to single tenant, in this example "customers" 
![image](https://user-images.githubusercontent.com/2000816/147104810-6c25f25a-2511-48b6-9c7f-35f090484027.png)

Then when a user logs in with that role, they are automatically in that "Customer" tenant by default.

- Since this user/role only has access to a single tenant, then the "Switch tenant" button should not even show up:  
![image](https://user-images.githubusercontent.com/2000816/147105214-edbefcf9-d565-4cca-8005-c213cd40cf83.png)

- If the user/role has access to more than one tenant then when the user logs in then the user should be greeted with a similar screen to select the desired tenant (I might be spoiled with how Elastic does Spaces :smile: ). Maybe the "Select your tenant" modal could be changed to show a box/card per tenant including Global and Private:  
![image](https://user-images.githubusercontent.com/2000816/147105563-83658e70-bf83-4271-a1e2-b6567bdb924d.png)

- When a user/role only has one tenant and logs in they are automatically logged in on the Global tenant even though global is disabled for that tenant, (maybe a bug?):  

![image](https://user-images.githubusercontent.com/2000816/147108481-56256b13-e2b3-427a-b7e7-1a3dfa865ca5.png)
 
- If Global and Private are disabled, Is there any reason to show them as disabled? Why not just not show them at all?

- Right now if a user wants to change tenants it is a little hard to find. Elastic has it next to their "hamburger" menu, which makes it more accessible :  
![image](https://user-images.githubusercontent.com/2000816/147105932-50e0f1f0-41e1-4c61-a121-4ec8571f0d62.png)

- Moving objects from one tenant to another is more complex than it should be. So far the only way I have seen to do something like this with OpenSearch Dashboards is to export/download the objects I want to move to my device, switch tenant and then re-upload/import them on the saved object screen. It would be nice to be able to copy objects from one tenant to another using the OpenSearch Dashboard UI. Elastic does have something that does this:  

![image](https://user-images.githubusercontent.com/2000816/147106425-5accf1e4-d4f8-41d4-99d6-99f42ea9153f.png)  

![image](https://user-images.githubusercontent.com/2000816/147106925-1b9412f2-4517-4fca-9a96-ef7355c0e0e1.png)

- It would be nice to be able to upload an icon per tenant. But that is just cosmetics :laughing: .

I know this is a lot and it is probably worth multiple GitHub issues, but I really want to switch to OpenSearch and this is the last blocker in my list to convince the company I work for. Let me know if you want me to create multiple issues for the things I have posted here! :+1:

**Comment by kunal-parsewar** [comment]
@yuxitang-amzn is this  feature implemented in any of the versions or it is planned in future releases? Could anyone confirm on this .

**Comment by davidlago** [comment]
The tenant selection features have changed since this report, and among other things tenant selection is remembered between logins (in the same browser). Closing this in favor of (and linking to) #53 for the workflow update suggestions from @derek-diaz as moving objects between tenants is in our radar. Thanks!

**Comment by josircg** [comment]
Hi @davidlago. I am using version 2.13.0 but everytime user logout, he has to switch tenant. This checkbox cited on this does not appears to it. 

Is there any other configuration that I have to set for the role or user?
