### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security-dashboards-plugin#845]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [x] Passing Build/CI on Windows
- [x] Documentation
- [x] #1171

**Comment by bbarani** [comment]
@cwperks Can you please update the current status?

**Comment by cwperks** [comment]
@peternied Please provide on update on running CI on windows

For the issue of not having a batch equivalent of the `install_demo_configuration.sh` (https://github.com/opensearch-project/security/issues/2148) there is a PR, but we are facing an issue with the automated validation of the change against main.

The `plugin_install` workflow has been extended to verify the installation on both linux and windows, but the issue being faced not is that an opensearch node cannot be started on the `windows-latest` runner because `windows-latest` runs as admin and the node will not start if its run as root. This is actively being worked on and we hope to find a solution shortly.

The build-time validation does work on 2.x, but only because the automatic backport of this change failed: https://github.com/opensearch-project/OpenSearch/pull/4656

**Comment by peternied** [comment]
This is queued up to be worked on next, as soon as I get the backend plugin ready for review for CI on Windows https://github.com/opensearch-project/security/pull/2190

**Comment by peternied** [comment]
Note, I'm moving the integration test work out into its own task.  It was not a core requirement for the windows platform release and we can fast follow to get it included.

**Comment by dblock** [comment]
I am not sure why we say integration tests weren't part of this work. Reopening. Let's close when there's no gap between testing on Linux and Windows.

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.

**Comment by peternied** [comment]
This is not complete, it is still a work in progress, I've removed the 2.4.0 label

**Comment by CEHENKLE** [comment]
@peternied What release are you targeting?

**Comment by peternied** [comment]
@CEHENKLE Missed the 2.5.0 release, targeting 2.6.0 @RyanL1997 is actively working this, see the follow PR for status:

- https://github.com/opensearch-project/security-dashboards-plugin/pull/1275

**Comment by cwperks** [comment]
https://github.com/opensearch-project/security-dashboards-plugin/pull/1275 has been merged. @peternied is there anything remaining for this ticket or can it be closed?

**Comment by peternied** [comment]
@RyanL1997 as the one who took this on, would you do the honors and close this issue?

**Comment by RyanL1997** [comment]
Closing this one since the https://github.com/opensearch-project/security-dashboards-plugin/pull/1275 has been merged. Thank you all for the support!
