### ISSUE TITLE
[BUG] /auth/logout cannot clear session info

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/security-dashboards-plugin#966]
Opening issue from an old one that had to be deleted. From @jezsy:

>It seems OpenSearch Dashboards does not properly invalidate sessions even after users explicitly log out.
>
>Steps to Reproduce
>
>    Log in to Dashboards
 >   Note value of generated cookie security_authentication
>    Log out of Dashboards via UI button
>    Use same security_authentication token and access Dashboards (e.g. url:5601/api/v1/configuration/account) - the session token still works
>
>The security plugin does seem to be keeping track of the sessions somehow, because it invalidates the cookie after around an >hour of inactivity. However, the log out button only clears the cookie in the browser but does not invalidate the session on the >server side immediately
>
>Using OpenSearch 1.2.3 and OpenSearch Dashboards 1.2.0 (with corresponding security plugins), with http_authenticator: basic >and authentication_backend: intern

**Comment by hardik-k-shah** [comment]
This issues is due to how security plugin does session management.

Security plug-in manages session at client side and there is no server side session management. So during logout it only clear out the cookie and can't invalidate the session (as there is no session information at server side to invalidate it).

So, if someone present same session token which was not expired, it is valid.

**Comment by jezsy** [comment]
Thanks for the feedback @hardik-k-shah 

Do I understand correctly that cookie expiration is directly baked into the value of security_authentication itself? And hence why the cookie value is changing every access because the cookie expiry is being extended, due to session keepalive defaulting to true?

Is this documented anywhere, how Dashboards security handles session management? Tried to find in OpenSearch docs but couldn't seem to find any. The closest I could find was this reference in SearchGuard: https://docs.search-guard.com/latest/kibana-authentication-http-basic. Some of the parameters described here seem to still work, but would be nice to have them officially documented

Lastly, are there plans to improve/modify this behavior? I believe in Kibana it was addressed by this issue: https://github.com/elastic/kibana/issues/17870

**Comment by peternied** [comment]
Thanks @davidlago for bringing up this issue.  The session token that is granted has a time limit associated with it, until that limit has expired the token is still valid, closing this out as this is by design.

As updates are made to sessions management it possible improvements will be made, during those proposals and designs features like this will be up for consideration.
